/**
 * Map helpers for the trip planner's map view.
 *
 * These utilities transform itinerary Activity_Blocks into map-ready data:
 *  - convert blocks (which may lack coordinates) into typed pins,
 *  - group pins by day,
 *  - assign a distinct, stable color per day, and
 *  - build chronological route segments within each day.
 *
 * They are intentionally pure and framework-free so they can be unit-tested
 * without a DOM or Leaflet.
 */

import type { ActivityCategory } from '@trip-planner/shared';

/** A single map marker derived from an Activity_Block with valid coordinates. */
export interface MapPin {
  blockId: string;
  latitude: number;
  longitude: number;
  title: string;
  category: ActivityCategory;
  dayNumber: number;
  /** Start time as "HH:mm" (24h), or null when unscheduled. */
  startTime: string | null;
}

/** A directed connection between two consecutive pins within the same day. */
export interface RouteSegment {
  from: MapPin;
  to: MapPin;
  /** Straight-line/route distance in meters. Null until enriched by routing. */
  distance: number | null;
  /** Travel duration in seconds. Null until enriched by routing. */
  duration: number | null;
}

/**
 * Minimal shape of an Activity_Block needed to build pins. Accepts the full
 * ActivityBlock as well as lighter client-side representations, as long as the
 * mapping fields are present.
 */
export interface BlockLike {
  id: string;
  title: string;
  category: ActivityCategory;
  latitude: number | null;
  longitude: number | null;
  startTime: string | null;
  /** The day this block belongs to. */
  dayNumber: number;
}

/**
 * Curated palette of visually distinct, high-contrast colors used for the
 * first several days. Chosen to remain distinguishable on an OSM basemap.
 */
const DAY_COLOR_PALETTE: string[] = [
  '#e6194b', // red
  '#3cb44b', // green
  '#4363d8', // blue
  '#f58231', // orange
  '#911eb4', // purple
  '#008080', // teal
  '#f032e6', // magenta
  '#9a6324', // brown
  '#808000', // olive
  '#000075', // navy
];

/**
 * Converts an HSL color to a #rrggbb hex string.
 * h in [0,360), s and l in [0,1].
 */
function hslToHex(h: number, s: number, l: number): string {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hp = h / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  let r = 0;
  let g = 0;
  let b = 0;
  if (hp >= 0 && hp < 1) [r, g, b] = [c, x, 0];
  else if (hp < 2) [r, g, b] = [x, c, 0];
  else if (hp < 3) [r, g, b] = [0, c, x];
  else if (hp < 4) [r, g, b] = [0, x, c];
  else if (hp < 5) [r, g, b] = [x, 0, c];
  else [r, g, b] = [c, 0, x];
  const m = l - c / 2;
  const toHex = (v: number) =>
    Math.round((v + m) * 255)
      .toString(16)
      .padStart(2, '0');
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

/**
 * Assigns a distinct color to each day number from 1..totalDays.
 *
 * The first {@link DAY_COLOR_PALETTE} days use hand-picked colors; beyond that
 * colors are generated by evenly spacing hues around the wheel so every day
 * still receives a unique, deterministic color.
 *
 * @param totalDays number of days in the trip (values <= 0 yield an empty map)
 * @returns Map keyed by dayNumber (1-based) -> "#rrggbb" hex color
 */
export function assignDayColors(totalDays: number): Map<number, string> {
  const colors = new Map<number, string>();
  if (!Number.isFinite(totalDays) || totalDays <= 0) return colors;

  const count = Math.floor(totalDays);
  for (let day = 1; day <= count; day++) {
    if (day <= DAY_COLOR_PALETTE.length) {
      colors.set(day, DAY_COLOR_PALETTE[day - 1]);
    } else {
      // Spread remaining hues evenly to keep them distinct from one another.
      const overflowIndex = day - DAY_COLOR_PALETTE.length - 1;
      const overflowTotal = Math.max(1, count - DAY_COLOR_PALETTE.length);
      const hue = Math.round((overflowIndex / overflowTotal) * 360);
      colors.set(day, hslToHex(hue, 0.65, 0.5));
    }
  }
  return colors;
}

/**
 * Converts Activity_Blocks into map pins, keeping only those with both a
 * latitude and longitude. Blocks missing either coordinate are dropped.
 */
export function toMapPins(blocks: BlockLike[]): MapPin[] {
  const pins: MapPin[] = [];
  for (const block of blocks) {
    if (
      block.latitude == null ||
      block.longitude == null ||
      Number.isNaN(block.latitude) ||
      Number.isNaN(block.longitude)
    ) {
      continue;
    }
    pins.push({
      blockId: block.id,
      latitude: block.latitude,
      longitude: block.longitude,
      title: block.title,
      category: block.category,
      dayNumber: block.dayNumber,
      startTime: block.startTime,
    });
  }
  return pins;
}

/**
 * Groups pins by their day number.
 *
 * The returned map is ordered by ascending day number, and within each day the
 * pins are ordered chronologically by {@link comparePinsByTime}.
 */
export function groupPinsByDay(pins: MapPin[]): Map<number, MapPin[]> {
  const grouped = new Map<number, MapPin[]>();
  for (const pin of pins) {
    const existing = grouped.get(pin.dayNumber);
    if (existing) existing.push(pin);
    else grouped.set(pin.dayNumber, [pin]);
  }

  // Sort each day's pins chronologically.
  for (const dayPins of grouped.values()) {
    dayPins.sort(comparePinsByTime);
  }

  // Return a map ordered by ascending day number.
  return new Map([...grouped.entries()].sort((a, b) => a[0] - b[0]));
}

/**
 * Parses an "HH:mm" time string into minutes since midnight.
 * Returns null for null/empty/malformed input.
 */
function timeToMinutes(time: string | null): number | null {
  if (!time) return null;
  const match = /^(\d{1,2}):(\d{2})$/.exec(time.trim());
  if (!match) return null;
  const hours = Number(match[1]);
  const minutes = Number(match[2]);
  if (hours > 23 || minutes > 59) return null;
  return hours * 60 + minutes;
}

/**
 * Orders two pins chronologically by start time. Pins without a start time are
 * placed after timed pins; ties fall back to a stable title/blockId compare.
 */
function comparePinsByTime(a: MapPin, b: MapPin): number {
  const ta = timeToMinutes(a.startTime);
  const tb = timeToMinutes(b.startTime);
  if (ta != null && tb != null && ta !== tb) return ta - tb;
  if (ta != null && tb == null) return -1;
  if (ta == null && tb != null) return 1;
  // Deterministic tiebreaker so ordering is stable across runs.
  return a.blockId.localeCompare(b.blockId);
}

/**
 * Builds route segments connecting consecutive pins within each day in
 * chronological (start-time) order.
 *
 * Pins are grouped by day; within a day the pins are ordered by start time and
 * a segment is emitted between each adjacent pair. Days with fewer than two
 * pins contribute no segments. Distance and duration are left null for a later
 * routing step to populate.
 */
export function buildRouteSegments(pins: MapPin[]): RouteSegment[] {
  const segments: RouteSegment[] = [];
  const byDay = groupPinsByDay(pins);

  for (const dayPins of byDay.values()) {
    for (let i = 0; i < dayPins.length - 1; i++) {
      segments.push({
        from: dayPins[i],
        to: dayPins[i + 1],
        distance: null,
        duration: null,
      });
    }
  }
  return segments;
}

/**
 * Computes a reasonable [lat, lng] center for a set of pins by averaging their
 * coordinates. Returns null when there are no pins (caller should fall back to
 * a geocoded destination or a sensible default).
 */
export function computePinsCenter(pins: MapPin[]): [number, number] | null {
  if (pins.length === 0) return null;
  let latSum = 0;
  let lngSum = 0;
  for (const pin of pins) {
    latSum += pin.latitude;
    lngSum += pin.longitude;
  }
  return [latSum / pins.length, lngSum / pins.length];
}
